org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=false
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

mappings=2024.11.17

# Environment Properties
minecraft_version=1.21.1
minecraft_version_range=[1.21.1]
neo_version=21.1.234
loader_version_range=[1,)

## Mod Properties
mod_id=jammies
mod_name=Jammies
mod_license=MIT
mod_version=1.1.0
mod_group_id=io.github.violethale.jammies
mod_authors=VioletHale
mod_description=A rework of TFC's Jams.

# Dependencies
tfc_version=4.2.10
patchouli_version=1.21.1-92-NEOFORGE

firmalife_version=3.0.8
kubastfca_version=7175406

jei_version=19.25.0.321
emi_version=1.1.22+1.21.1
jade_version=15.10.0+neoforge